# TODO
Feature: Room Type Update
    * A room type name cannot be null or empty
    * the capacity of the room type cannot be < 0
    * the size of the room type cannot be < 0
    * You can add/delete mulitple rooms under a room type, and each room must have:
    * wholesale price cannot be greater than retail price
    * the retail price cannot <= 0
    * tax rate cannot be negative
    * the cover image cannot be deleted, you should delete the image after changing the cover image

  Background:
    Given a hotelier
    And a room type with name 'Standard', description 'pretty nice', capacity 2, size: 16
    And has price information of wholesale price 500, retail_price 1000, tax rate 0
    And has facility 'WiFi'
    And has a room with roomNo '101', floor 'first', extra information 'first one'
    And has an cover image 'cover.jpg' and an image 'image.jpg'

  Scenario: Update basic information
    Given ...
    When ...
    Then ...

  Scenario: Diable the room type
    Given ...
    When ...
    Then ...

  Scenario: Enable the room type
    Given ...
    When ...
    Then ...

  Scenario: Update room information
    Given ...
    When ...
    Then ...

  Scenario: Activate a room
    Given ...
    When ...
    Then ...

  Scenario: Disactivate a room
    Given ...
    When ...
    Then ...

  Scenario: Add facilities
    Given ...
    When ...
    Then ...

  Scenario: Remove facilities
    Given ...
    When ...
    Then ...

  Scenario: Update room type price
    Given ...
    When ...
    Then ...

  Scenario: Add new images
    Given ...
    When ...
    Then ...

  Scenario: Remove images
    Given ...
    When ...
    Then ...

  Scenario: Set the new cover image
    Given ...
    When ...
    Then ...

  Scenario: Cover image cannot be deleted
    Given ...
    When ...
    Then ...

  Scenario Outline: A hotelier creates a room type with basic information
    Given a hotelier
    And the hotelier has input room data "<name>", <capacity>
    And add a new room with "<roomNo>"
    When the hotelier creates the room type
    Then the room type and the room are created
    And wholesale_price, retail_price, and tax_rate are all 0
    But the room type status is disabled
    And the room status is inactive

    Examples:
      | name     | capacity | roomNo |
      | Standard | 2        | 101    |
      | Single   | 1        | 102    |

  Scenario Outline: A hotelier creates a room type with detailed information
    Given a hotelier
    And the hotelier has input room data "<name>", "<description>", <capacity>, <size>
    And input price information "<wholesale_price>", "<retail_price>", "<tax_rate>"
    And input facilities "<facilities>"
    And add a new room with "<roomNo>", "<floor>", "<extra_information>"
    And upload an image "<image>"
    When the hotelier creates the room type
    Then the room type and the room are created
    And the first image is the cover image
    But the room type status is disabled
    And the room status is inactive

    Examples:
      | name     | description | capacity | size | wholesale_price | retail_price | tax_rate | facilities           | roomNo | floor | extra_information |
      | Standard | pretty nice | 2        | 16   | 500             | 1000         | 0        | ["Wifi", "BathRoom"] | 101    | first | first one         |